#!/bin/sh

bspc_node_swap_directionmost() {
  bspc node -s "$1"
  until [ $? -ne 0 ]; do
    bspc node -s "$1"
  done
}


SELECTOR=$1

bspc node -s "$SELECTOR"

if [ $? -ne 0 ]; then
  case "$SELECTOR" in
    "east")
      DIRECTION="next"
      SELECTOR="west"
      ;;
    "west")
      DIRECTION="prev"
      SELECTOR="east"
      ;;
  esac
  if [ -n "$DIRECTION" ]; then
    bspc node -d "$DIRECTION" --follow
    bspc_node_swap_directionmost "$SELECTOR"
  fi
fi
