#!/bin/sh

bspc_node_focus_directionmost() {
  bspc node -f "$1"
  until [ $? -ne 0 ]; do
    bspc node -f "$1"
  done
}


SELECTOR=$1

bspc node -f "$SELECTOR"

if [ $? -ne 0 ]; then
  case "$SELECTOR" in
    "east")
      DIRECTION="next"
      SELECTOR="west"
      ;;
    "west")
      DIRECTION="prev"
      SELECTOR="east"
      ;;
  esac
  if [ -n "$DIRECTION" ]; then
    bspc desktop -f "$DIRECTION"
    bspc_node_focus_directionmost "$SELECTOR"
  fi
fi
