#!/bin/sh

GRAB=$1
SCREENSHOT_DIR_PATH=$2

LOCATION="$SCREENSHOT_DIR_PATH/$(date +"%y-%m-%d+%T").png"

case "$GRAB" in
  "no")
    ARG=""
    ;;
  "yes")
    ARG="-s"
    ;;
esac

scrot $ARG "$LOCATION"

xclip -selection clipboard -t image/png -i "$LOCATION"
