#!/bin/sh

ACTIVE_WINDOW=$(xdotool getactivewindow)
ACTIVE_WM_CLASS=$(xprop -id "$ACTIVE_WINDOW" | grep WM_CLASS)

[[ "$ACTIVE_WM_CLASS" != *"Alacritty"* ]] && exec alacritty

PID=$(xprop -id "$ACTIVE_WINDOW" | grep _NET_WM_PID | grep -oP "\d+")
CHILD_PID=$(pgrep -P $PID)
if [[ "$PID" == "" ]]
then
    exec alacritty
fi

pushd "/proc/$CHILD_PID/cwd"
SHELL_CWD=$(pwd -P)
popd

exec alacritty --working-directory "$SHELL_CWD"
