#!/bin/sh

LAYOUT=$(bspc query -T -d | jq -r .layout);
SELECTOR=$1

if [ "$LAYOUT" = monocle ]; then
  case "$SELECTOR" in
    "north")
      DIRECTION='prev.local.!hidden.window'
      ;;
    "south")
      DIRECTION='next.local.!hidden.window'
      ;;
  esac
else
  DIRECTION="$SELECTOR"
fi
bspc node -f "$DIRECTION"
