# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      ./default.nix
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fa57cbd5-6383-4a55-b60a-b96cbe135a0b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-84f99b3c-3797-4fb7-b3b8-47b048b53a50".device = "/dev/disk/by-uuid/84f99b3c-3797-4fb7-b3b8-47b048b53a50";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7616-B10C";
      fsType = "vfat";
    };

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/9e127c97-98f8-4aab-b086-4672488084e9";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
