# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      ./default.nix
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/crypto";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    };

  boot.initrd.luks.devices."crypto".device = "/dev/nvme0n1p2";

  fileSystems."/boot" =
    { device = "/dev/nvme0n1p1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/crypto";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/persistent" =
    { device = "/dev/mapper/crypto";
      neededForBoot = true;
      fsType = "btrfs";
      options = [ "subvol=persistent" "compress=zstd" "noatime" ];
    };

  fileSystems."/mnt/data" =
    { device = "/dev/sda1";
      fsType = "ext4";
    };

  fileSystems."/persistent/home/z/.steam" = {
    depends = [
      "/persistent"
      "/mnt/data"
    ];
    device = "/mnt/data/home/z/.steam";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/persistent/home/z/.local/share/Steam" = {
    depends = [
      "/persistent"
      "/mnt/data"
    ];
    device = "/mnt/data/home/z/SteamShare";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/persistent/home/z/.local/share/lutris" = {
    depends = [
      "/persistent"
      "/mnt/data"
    ];
    device = "/mnt/data/home/z/LutrisShare";
    fsType = "none";
    options = [ "bind" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
